node{

    stage('Print Message') {      //打印信息
      echo '打印信息'
      echo "Project_Pipeline_name: ${JOB_NAME}"
      echo "Project_module_name: ${PROJECT_NAME}"
      echo "workspace: ${WORKSPACE}"
      echo "branch: ${Branch_name}"           //gitlab分支名
      echo "build_id: ${BUILD_ID}"
      echo "target_action: ${action}"
      echo "registryUrl: ${registryUrl}"
      echo "image_repository: ${registryUrl}/${Project_name}"
    }

    //此步骤在调试Jenkinsfile时可以注释以便了解目录结构
    stage('Clean') {         //清理工作目录
      echo "清理工作目录: ${WORKSPACE}"
      deleteDir()     //表示删除当前目录(${WORKSPACE})下内容，通常用在构建完毕之后清空工作空间
    }

    stage('Checkout'){
        //check CODE
      git credentialsId: 'git-key',
      url: 'https://github.com/Vigin-Tse/sct.git'
    }

    //定义mvn环境
    def mvnHome = tool 'maven'
    env.PATH = "${mvnHome}/bin:${env.PATH}"

    stage('Project Packaging & Deploy'){
        //mvn构建
        sh "mvn clean -Dmaven.test.skip=true deploy -pl sct-common"
    }

//    stage('Image Build & Deploy'){
//    def imagesName = '172.18.118.25:9003/sct-eureka:lastest -f ./${Project_name}/DockerFile'
//        docker.build(imagesName).push()
//    }

}